### ISSUE TITLE
wrong _LOCK_T

### ISSUE THREAD

**Issue by rofl0r** [pspdev/newlib#9]
@fjtrujy 
after updating my toolchain to <strike>this</strike> newlib version **4.4.0**, i get a compile error for pspsdk trying to dereference _LOCK_T, which is defined to int in sys/lock.h because _RETARGETABLE_LOCKING is not set. (that probably needs to go into newlib.h).

**Comment by rofl0r** [comment]
it seems activated by --enable-newlib-retargetable-locking - it'd be nice if that happens automatically when building for psp.

**Comment by fjtrujy** [comment]
I thought that this flag is part of the parameters  we had in the compilation scripts

**Comment by fjtrujy** [comment]
Here you have it.
https://github.com/pspdev/psptoolchain-allegrex/blob/main/scripts/003-newlib.sh#L47

**Comment by rofl0r** [comment]
thanks. i've been building my own toolchain based on your patches, and the newlib 4.1 patch was self-contained (i.e. it didnt require to set additional options).
now testing this new newlib based toolchain, there are several odd things happening. for one, newlib thinks we have fork because -DNO_FORK isn't set and expects _fork_r from libcglue. same for -D_NO_POPEN
next psp cglue has lots of backend functions for pipe(), yet they are not called from newlib. wait() now calls _wait_r, not _wait, etc. either i'm missing something big here, or the current newlib integration is half broken.

**Comment by fjtrujy** [comment]
I don’t fully remember all the details, but please create a dummy example using the current toolchain where we can actually double-check if it is working as expected.
Maybe with the migration to newlib 4.3 I made some mistakes.
Cheers!

**Comment by rofl0r** [comment]
here's a script that takes libc.a, libcglue.a and libgcc.a and cross-checks the missing symbols:

```py
#!/usr/bin/env python2
import subprocess, sys, os, re

def shellcmd(cmd):
	proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	out, err = proc.communicate()
	ec = proc.returncode
	return ec, out, err

# D: data
# C: common
# S: small data
# G: small data, initialized
# R: read-only data
# T: function defined
# U: undefined sym
# C: uninit. data sym defined in obj
# B: uninit. data sym defined in binary
# D: init. data sym defined in obj/binary
# R: r/o (const) data sym defined in obj/binary
def get_object_syms(obj):
	nm = os.environ['NM'] if 'NM' in os.environ else 'nm'
	ec, out, err = shellcmd('%s %s'%(nm, obj))
	if ec:
		sys.stderr.write(err)
		return None
	rex = re.compile('([0-9a-f]+|[ ]+) ([A-Za-z]) (.*)')
	syms = {}
	lines = out.split('\n')
	for line in lines:
		m = rex.match(line)
		if not m: continue
		addr, letter, sym = m.groups(0)
		if not letter in syms: syms[letter] = {}
		syms[letter][sym] = int(addr, 16) if len(addr) and addr[0] != ' ' else -1
	return syms

if len(sys.argv) != 4:
	print("error: need 3 parameters: 1. path to libc.a, 2. path to libcglue.a 3. path to libgcc.a")
	sys.exit(1)

libc = get_object_syms(sys.argv[1])
glue = get_object_syms(sys.argv[2])
gcc = get_object_syms(sys.argv[3])
print(">>> undefined symbols in libc.a without impl in libcglue:")
for x in libc['U'].keys():
	if x in libc['T'] or x in glue['T'] or x in gcc['T']: continue
	elif 'S' in libc and x in libc['S']: continue
	elif 'R' in libc and x in libc['R']: continue
	elif 'C' in libc and x in libc['C']: continue
	elif 'D' in libc and x in libc['D']: continue
	elif 'G' in libc and x in libc['G']: continue
	else: print(x)
print(">>> underscore symbols provided in libcglue not used by libc.a")
for x in glue['T']:
	if x[0] != '_' or x in libc['U']: continue
	print x
```

in my case, i already fixed _fork_r and popen by adding -DNO_FORK and -D_NO_POPEN to the newlib CFLAGS.

this is what the script outputs:
```
>>> undefined symbols in libc.a without impl in libcglue:
issetugid
_uc2jp_l
_init
_wait_r
execl
fork
getlogin
pipe
dup2
_mkdir
_jp2uc_l
sigprocmask
waitpid
_execve_r
__malloc_current_mallinfo
_fini
>>> underscore symbols provided in libcglue not used by libc.a
__fdman_init
__retarget_lock_try_acquire_recursive
__pipe_nonblocking_read
__socket_close
__retarget_lock_init
_wait
__retarget_lock_try_acquire
__fdman_release_descriptor
__pipe_close
__retarget_lock_close
__deinit_mutex
__get_drive
__set_errno
__init_cwd
__pipe_nonblocking_write
__fdman_get_dup_descriptor
__pipe_read
__pipe_peekmsgsize
__psp_free_heap
__pipe_write
__fdman_get_new_descriptor
__init_mutex
_fork
__path_absolute
```

**Comment by fjtrujy** [comment]
So I have been checking those symbols:
> undefined symbols in libc.a without impl in libcglue:

- `issetugid`: `__NETBSD_SYSCALLS` is needed to be set (this issue has been there probably since the very beginning)
- `_uc2jp_l`:  Not sure in wich scenario can be used, but in theory how we don't support `_MB_CAPABLE`, this shouldn't be called.
- `_init`: It is called from `__libc_init_array` which looks to be something that must be called in crt0, however we aren't calling it, maybe we have here an issue...
- `_wait_r`: This shouldn't be used as we have the flag `-DNO_EXEC`...
- `execl`: This shouldn't be used as we have the flag `-D_NO_EXECVE` ...
- `fork`: Used by `wordexp`, this looks to be an issue in newlib, as probably this whole file shouldn't be compiled
- `getlogin`: We can provide dummy implementation in `libcglue`
- `pipe`: Used by `wordexp`, this looks to be an issue in newlib, as probably this whole file shouldn't be compiled
- `dup2`: Used by `wordexp`, this looks to be an issue in newlib, as probably this whole file shouldn't be compiled
- `_mkdir`: Used by `_mkdir_r` however, this `_mkdir_r` is never called, once again looks to be an issue in newlib as probably this whole file shouldn't be compiled.
- `_jp2uc_l`: Not sure in wich scenario can be used, but in theory how we don't support `_MB_CAPABLE`, this shouldn't be called.
- `sigprocmask`: Probably we can create a dummy implementation in libcglue
- `waitpid`: Used by `wordexp`, this looks to be an issue in newlib, as probably this whole file shouldn't be compiled
- `_execve_r`: This shouldn't be used as we have the flag `-DNO_EXEC`...
- `__malloc_current_mallinfo`: Not really sure where this is used/called....
- `_fini`: It is called from `__libc_fini_array` which looks to be something that must be called in crt0, however we aren't calling it, maybe we have here an issue...


> underscore symbols provided in libcglue not used by libc.a
I think your script has something missing as the majority of the next symbols are used. Some methods start by `_`, because we wanted to make them "private" but they are still being used by some other files in `libcglue`. 
Also not sure if you took into consideration the `crt0` file.

- `__fdman_init`: Used by `__libcglue_init` in crt0
- `__retarget_lock_try_acquire_recursive`: There is not much information about this API in newlib, maybe it is not used/needed....
- `__pipe_nonblocking_read`: Used by `_read` in `libcglue`
- `__socket_close`: Used by `_close` in `libcglue`
- `__retarget_lock_init`: There is not much information about this API in newlib, maybe it is not used/needed....
- `_wait`: This should be used by `wait`, I will double check it.
- `__retarget_lock_try_acquire`: There is not much information about this API in newlib, maybe it is not used/needed....
- `__fdman_release_descriptor`: Used in several places in `libcglue`.
- `__pipe_close`: Used in `_close` in `libcglue`
- `__retarget_lock_close`: There is not much information about this API in newlib, maybe it is not used/needed....
- `__deinit_mutex`: Called in the `__libcglue_deinit` which is called in `_exit` in `libcglue`
- `__get_drive`: Called in several places on `libcglue`
- `__set_errno`: Called tons of places in `libcglue`
- `__init_cwd`: Called during init on `__libcglue_init`, which is called on `crt0`
- `__pipe_nonblocking_write`: Called on `_write` in `libcglue`
- `__fdman_get_dup_descriptor`: Called in a couple of places in libcglue
- `__pipe_read`: Called in `_read` in `libcglue`
-`__pipe_peekmsgsize`: Use several times in the `pipe.c`
- `__psp_free_heap`: Use on `__libcglue_deinit` during deinit
- `__pipe_write`: Used on `_write` in `libcglue`
- `__fdman_get_new_descriptor`: Used in several places on `libcglue`
- `__init_mutex`: Used on `__libcglue_init`
- `_fork`: In theory this should be called by `fork` in `newlib`, I will double check it.
- `__path_absolute`: Used on tons of places in `libcglue`.


So to make a summary, keep in mind that we are still in the process of making `PSPDEV` as POSIX as possible.
We are just progressing as soon as we see something missing or wrong, also sometimes we just provide dummy functions to avoid compilation issues but knowing that behavior is not the good one.


Regarding all the functions you mentioned, I think that just `_init` and `_fini` are the most important things that I see missing in our implementation.
The remaining things look to be either issues on `newlib`, or maybe uncompleted POSIX implementation on our that no one complained yet.

**Comment by fjtrujy** [comment]
Actually after double-checking implementation once again `_init` and `_fini` both are called from `crt0`. So I would say that implementation is right.
https://github.com/pspdev/pspsdk/blob/master/src/startup/crt0.c#L78-L82

**Comment by fjtrujy** [comment]
Regarding `fork`.
Maybe I'm missing something but we have:
1. `fork` is implemented on `newlib/libc/syscalls/sysfork.c`, which call `_fork_r`
```c
#ifndef NO_FORK

#include <reent.h>
#include <unistd.h>

int
fork (void)
{
  return _fork_r (_REENT);
}

#endif
```
2. Then `_fork_r` is implemented on `newlib/libc/reent/execr.c`, which call `_fork`
```c
#ifndef NO_FORK

int
_fork_r (struct _reent *ptr)
{
  int ret;

  errno = 0;
  if ((ret = _fork ()) == -1 && errno != 0)
    _REENT_ERRNO(ptr) = errno;
  return ret;
}

#endif
```
3. Finally `_fork` is implemented on `src/libcglue/glue.c`
```c
#ifdef F__fork
pid_t _fork(void)
{
	errno = ENOSYS;
	return (pid_t) -1; /* not supported */
}
#endif
```

If I'm right we aren't setting `NO_FORK` flag during newlib configuration so, as you can guess `fork` implementation at the end is not implemented as we return a `-1`, but in theory software using `fork` should be able to link properly.

**Comment by fjtrujy** [comment]
Regarding `_NO_POPEN` happens something similar.
We aren't setting `_NO_POPEN` flag during newlib configuration, so `newlib/libc/posix/popen.c` file will be compiled which internally uses `pipe`
```c
#ifndef _NO_POPEN

/////// Some other lines

FILE *
popen (const char *program,
	const char *type)
{
	struct pid *cur;
	FILE *iop;
	int pdes[2], pid;

       if ((*type != 'r' && *type != 'w')
	   || (type[1]
#ifdef HAVE_FCNTL
	       && (type[2] || (type[1] != 'e'))
#endif
			       )) {
		errno = EINVAL;
		return (NULL);
	}

	if ((cur = malloc(sizeof(struct pid))) == NULL)
		return (NULL);

	if (pipe(pdes) < 0) {
		free(cur);
		return (NULL);
	}
/////// Some other lines
```

And finally `pipe` implementation is on `src/libcglue/pipe.c`
```c
#ifdef D_pipe
int pipe(int fildes[2])
{
	static int iIndex = 0;
	char name[32];
	iIndex++;

	sprintf(name, "__pipe_%02d", iIndex);

	SceUID uid = sceKernelCreateMsgPipe(name, PSP_MEMORY_PARTITION_USER, 0, (void *)PIPE_BUF, NULL);

	if (uid >= 0) {
		fildes[0] = __fdman_get_new_descriptor();
		if (fildes[0] != -1) {
			__descriptormap[fildes[0]]->descriptor = uid;
			__descriptormap[fildes[0]]->type = __DESCRIPTOR_TYPE_PIPE;
		} 
		else {
			sceKernelDeleteMsgPipe(uid);
			errno = EFAULT;
			return -1;
		}
		
		fildes[1] = __fdman_get_dup_descriptor(fildes[0]);
		if (fildes[1] != -1) {
			__descriptormap[fildes[1]]->descriptor = uid;
			return 0;
		} 
		else {
			sceKernelDeleteMsgPipe(uid);
			errno = EFAULT;
			return -1;
		}
		
	}
	else {
		errno = EFAULT;
		return -1;
	}
}
#endif
```

So once again, everything looks to be right.

**Comment by fjtrujy** [comment]
After re-checking configs looks like we should remove `NO_EXEC` from flag, because this is avoiding the compilation of `execr.c`.
Maybe we should also do something similar for `_NO_EXECVE` however this will require to implement more dummy functions.
I will do it.
Cheers

**Comment by fjtrujy** [comment]
@rofl0r take a look at https://github.com/pspdev/newlib/pull/10 and https://github.com/pspdev/pspsdk/pull/188

**Comment by rofl0r** [comment]
thanks for taking a look. i found these issues when trying to compile libmad whose configure script now detects waitpid fcntl pipe fork and activates codes using them, but then one gets link errors when linking the lib against one's code. same for libid3tag, it now detects ftruncate, but when linking it's not there. i didn't yet figure out why it detects some of those, it's as if the linker thinks those symbols are available when they're only present as undefined.

regarding the "syms provided by glue not used by libc": ouch, i forgot to remove those referenced by libglue itself.

> After re-checking configs looks like we should remove NO_EXEC from flag, because this is avoiding the compilation of execr.c.

indeed, that 's what caused _fork_r to not get compiled. maybe it would be better to disable both NO_EXEC and NO_FORK ? otherwise these syms will be available in libc and stuff using autoconf will then activate optional functionality using them.

**Comment by rofl0r** [comment]
> @rofl0r take a look at https://github.com/pspdev/newlib/pull/10 and https://github.com/pspdev/pspsdk/pull/188

apart from using _Nullable it seems alright, if you want to go the route of pretending functionality is there which only returns ENOSYS.

though it seems the most pressing issue is, as you figured out, the compilation of wordexp, tearing behind it a bunch of undefined symbols.

**Comment by rofl0r** [comment]
> #ifdef D_pipe

maybe this should be F_pipe ? it is at least for all other syms.

**Comment by fjtrujy** [comment]
> D_pipe

Nice catch!

**Comment by fjtrujy** [comment]
Amended that change to pspsdk PR.

**Comment by fjtrujy** [comment]
I think we can close this issue thanks of #10

**Comment by rofl0r** [comment]
i'll rebuild newlib/pspsdk with those changes and let you know which issues remain. though i'm quite certain that wordexp should be disabled.

**Comment by rofl0r** [comment]
alright, the new toolchain passes initial testing. i can now compile libmad and libid3tag without having undefined references to fork, pipe, ftruncate etc when linking. i'll file a new issue/pr if i run into problems compiling other packages that are due to wrong newlib configuration.
